### ISSUE TITLE
Checklist for CF 1.7 implementation

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#664]
# Checklist of tasks to implement for CF 1.7 milestone
*Feel free to update or make suggestions as needed*

- [x] [#31](https://cf-trac.llnl.gov/trac/ticket/31) Adding an attribute for `actual_range` , see [Section 2.5.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#missing-data)
- [x] [#118](https://cf-trac.llnl.gov/trac/ticket/118), Add `geoid_name` and `geopotential_datum_name` to the list of Grid Mapping Attributes. see [Table F1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#table-grid-mapping-attributes)
- [x] [#148](https://cf-trac.llnl.gov/trac/ticket/148) Added `maximum_absolute_value`, Added maximum_absolute_value, minimum_absolute_value and mean_absolute_value to cell methods in [Appendix E ](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-cell-methods)
- [x] [#77](https://cf-trac.llnl.gov/trac/ticket/77), Add sinusoidal projection [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_sinusoidal)
- [x] [#92](https://cf-trac.llnl.gov/trac/ticket/92) Add oblique mercator projection, see [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_oblique_mercator)
- [x]  [#72](https://cf-trac.llnl.gov/trac/ticket/72), Adding the [geostationary projection](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_geostationary_projection)
- [x] [#102](https://cf-trac.llnl.gov/trac/ticket/102), additional `cell_methods` (`root_mean_square` and `sum_of_squares`) , changes in Appendix E and section 7.3; see [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-cell-methods)

- [x]  [#61](https://cf-trac.llnl.gov/trac/ticket/61) Two new cell methods Appendix E
  `root_mean_square` and `mean_of_upper_decile`
- [x] [#65](https://cf-trac.llnl.gov/trac/ticket/65) Add `range` to `cell_methods`
- [x] [#69](https://cf-trac.llnl.gov/trac/ticket/69) `crs_wkt` attribute in grid_mapping 
- [x] [#93](https://cf-trac.llnl.gov/trac/ticket/93) Two new dimensionless coordinates ("ocean_s_coordinate_g1" and "ocean_s_coordinate_g2" in Appendix D)
- [x] [#87](https://cf-trac.llnl.gov/trac/ticket/87) Allow comments in coordinate variables
Currently, the Compliance Checker does not check if attributes are in the *wrong* place.

- [x] [#143](https://cf-trac.llnl.gov/trac/ticket/143) Supplement the definitions of dimensionless vertical coordinates
~~- [x] [#75](https://cf-trac.llnl.gov/trac/ticket/75) **?** Fix documentation and definitions of 3 grid mapping definitions~~ (appears to be CF documentation related, marking as implemented)
- [x] [#109](https://cf-trac.llnl.gov/trac/ticket/109) resolve inconsistency of positive and standard_name attributes.  *NB: doesn't seem to be a way to implement this in a machine readable way; marking as implemented*
- ~~[x] [#76](https://cf-trac.llnl.gov/trac/ticket/76) More than one name in Conventions attribute (section 2.6.1) *Base code already splits along spaces and commas.  CF 1.7 conventions check does not appear to be properly implemented.*~~
- [x] [#86](https://cf-trac.llnl.gov/trac/ticket/86) Allow coordinate variables to be scaled integers
- [x] [#80](https://cf-trac.llnl.gov/trac/ticket/80), added attributes to AppF Table F1, changes in section 5.6 and 5.6.1. (`grid_mapping` attributes 
    - `horizontal_datum_name`
    - `towgs84` (a double-precision array, with 3, 6 or 7 values)
    - `prime_meridian_name`
    - `reference_ellipsoid_name`
    - `projected_coordinate_system_name`
    - `geographic_coordinate_system_name`
- [x] [#70](https://cf-trac.llnl.gov/trac/ticket/70) Connecting coordinates to Grid Mapping variables: revisions in Section 5.6 and Examples 5.10 and 5.12

**Comment by benjwadams** [comment]
Looks like everything has been implemented. Closing this issue.
